apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r57rp4ttm-go 
  janus-idp.io/tekton: r57rp4ttm-go
  backstage.io/kubernetes-id: r57rp4ttm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r57rp4ttm-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml